name: "Intercept bad issues"

on:
  issues:
    types: [opened]

jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - name: Auto close issues that did not follow template
      uses: roots/issue-closer@v1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-pattern: "(\\[x\\]|\\[X\\]) I have read"
        issue-close-message: ":wave: Hi @${issue.user.login},\n\nThis issue is being automatically closed because it does not follow the issue template."
